# Generated by Django 3.1.1 on 2020-09-16 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20200916_1402'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ['-pub_date']},
        ),
        migrations.RenameField(
            model_name='ingredient',
            old_name='name',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='tag',
            name='style',
            field=models.CharField(max_length=255, null=True, verbose_name='Постфикс для стиля шаблона'),
        ),
    ]
