# Generated by Django 3.1.1 on 2020-09-07 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_remove_recipe_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='duration',
            field=models.IntegerField(verbose_name='Время приготовления'),
        ),
    ]
