# Generated by Django 3.1.1 on 2020-09-08 18:39

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0006_favorites_follow'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Favorites',
            new_name='Favors',
        ),
    ]
